version: 2.1

jobs:
  build-tag-deploy:
    # machine: true
    docker:
      - image: cimg/base:2021.02-20.04
    steps:
      # Checkout the code as the first step.
      - checkout
      # Build, Tag, Deploy
      - setup_remote_docker
      - run:
          name: Build
          command: docker build -t circleci-sample-docker-image .

workflows:
  build:
    jobs:
      - build-tag-deploy:
          context: sample_context
